services:
  zalo-server:
    build:
      context: .
      dockerfile: Dockerfile
    image: buildertv/multizlogin:latest
    container_name: zalo-server
    ports:
      - "3000:3000"
    volumes:
      - ./zalo_data:/app/zalo_data
    environment:
      - PORT=3000
      - MESSAGE_WEBHOOK_URL=${MESSAGE_WEBHOOK_URL}
      - GROUP_EVENT_WEBHOOK_URL=${GROUP_EVENT_WEBHOOK_URL}
      - REACTION_WEBHOOK_URL=${REACTION_WEBHOOK_URL}
    restart: always
    working_dir: /app
